name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: "${{ secrets.TEMI_SECRET }}"
