name: Run RenovateBot

on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on:  [self-hosted, renovatebot]
    environment:
      name: cdc-coe-botfrey
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          echo "Downloading Github App private key..."
          echo "${{ secrets.CDC_COE_BOTFREY_PEM }}" > app-private-key.pem
          
          npm run renovate